---
title: "Rock climbing survey data claning & t-test"
author: "Sunny Tseng"
date: "2023-03-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### R packages
Here we install (by `install.packages()`) and load (by `library()`) the packages that we will need. A package is like a tool box in R, that includes many functions. For example, `tidyverse` package provides functions for data wrangling and data cleaning, `here` packages provides functions for working directory management.  
```{r, echo = FALSE}
#install.packages("tidyverse")
library(tidyverse)
#install.packages("here")
library(here)
library(readxl)
```


## Cohort 1

### Import data
```{r}
data_c1_s1 <- read_excel(here("data", 
                              "Cohort 1 Surveys_123_spreadsheets", 
                              "VIMFF Cohort 1 Survey 1_pre-intervention.xlsx"))

data_c1_s2 <- read_excel(here("data", 
                              "Cohort 1 Surveys_123_spreadsheets", 
                              "VIMFF Cohort 1 Survey 2_post-intervention.xlsx"))

data_c1_s3 <- read_excel(here("data", 
                              "Cohort 1 Surveys_123_spreadsheets", 
                              "VIMFF Cohort 1 Survey 3_post-post.xlsx"))

```


### Data cleaning
```{r}
new_name <- function(dataset, start, end){
  dataset[1, start:end] %>% as_vector()
}

data_c1_s1_clean <- data_c1_s1 %>%
  rename_with(.fn =~ new_name(data_c1_s1, 65, 84), .cols = c(65:84)) %>%
  unite(gender, names(.)[11:23], sep = ",", na.rm = TRUE) %>%
  unite(nationality, names(.)[12:28], sep = ",", na.rm = TRUE) %>%
  unite(indoor_style_practice, names(.)[24:26], sep = ",", na.rm = TRUE) %>%
  unite(outdoor_style_practice, names(.)[29:34], sep = ",", na.rm = TRUE) %>%
  mutate()
  
  filter(row_number() != 1) %>%
  select("Respondent ID", "gender", "nationality", 13:15, 30:49) 
  




```


### t-test










